# Generated by Django 4.2.30 on 2026-07-21 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_trade_accounts'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tradeaccount',
            new_name='finance_tra_account_e9c2ce_idx',
            old_name='finance_tra_account_8d922a_idx',
        ),
        migrations.RenameIndex(
            model_name='tradeaccount',
            new_name='finance_tra_partner_fd210e_idx',
            old_name='finance_tra_partner_297cc4_idx',
        ),
    ]
