# Generated by Django 4.2.30 on 2026-07-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0002_chat_retention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20),
        ),
    ]
