# Generated by Django 4.2.30 on 2026-07-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_ai', '0006_chatattachment_chatmessage_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='Percakapan Baru', max_length=150),
        ),
    ]
