from django.urls import path
from . import views
from cultivation.decorators import cycle_write_guard
app_name = 'operations'
urlpatterns = [
    path('import/<str:module>/', cycle_write_guard(views.import_excel), name='import_excel'),
    path('import/<str:module>/template/', views.download_import_template, name='download_import_template'),
    path('production-dashboard/', views.production_dashboard, name='production_dashboard'),
    path('parameter-dashboard/', views.parameter_dashboard, name='parameter_dashboard'),
    path('daily-records/', views.daily_records, name='daily_records'),
    path('daily-records/add/', cycle_write_guard(views.add_daily_record), name='add_daily_record'),
    path('daily-records/export/excel/', views.export_daily_records_excel, name='export_daily_records_excel'),
    path('daily-records/export/pdf/', views.export_daily_records_pdf, name='export_daily_records_pdf'),
    path('anco/', views.anco_checks, name='anco_checks'),
    path('anco/add/', cycle_write_guard(views.add_anco_check), name='add_anco_check'),
    path('anco/export/excel/', views.export_anco_excel, name='export_anco_excel'),
    path('anco/export/pdf/', views.export_anco_pdf, name='export_anco_pdf'),
    path('sampling/', views.sampling_records, name='sampling_records'),
    path('sampling/add/', cycle_write_guard(views.add_sampling_record), name='add_sampling_record'),
    path('sampling/export/excel/', views.export_sampling_excel, name='export_sampling_excel'),
    path('sampling/export/pdf/', views.export_sampling_pdf, name='export_sampling_pdf'),
    path('siphon/', views.siphon_records, name='siphon_records'),
    path('siphon/add/', cycle_write_guard(views.add_siphon_record), name='add_siphon_record'),
    path('siphon/export/excel/', views.export_siphon_excel, name='export_siphon_excel'),
    path('siphon/export/pdf/', views.export_siphon_pdf, name='export_siphon_pdf'),
    path('parameters/', views.parameters, name='parameters'),
    path('parameters/add/', cycle_write_guard(views.add_parameter), name='add_parameter'),
    path('parameters/export/excel/', views.export_parameters_excel, name='export_parameters_excel'),
    path('parameters/export/pdf/', views.export_parameters_pdf, name='export_parameters_pdf'),
    path('harvests/', views.harvests, name='harvests'),
    path('harvests/add/', cycle_write_guard(views.add_harvest), name='add_harvest'),
    path('harvests/export/excel/', views.export_harvests_excel, name='export_harvests_excel'),
    path('harvests/export/pdf/', views.export_harvests_pdf, name='export_harvests_pdf'),

    path('daily-records/<int:pk>/', views.daily_record_detail, name='daily_record_detail'),
    path('anco/<int:pk>/', views.anco_detail, name='anco_detail'),
    path('sampling/<int:pk>/', views.sampling_detail, name='sampling_detail'),
    path('siphon/<int:pk>/', views.siphon_detail, name='siphon_detail'),
    path('parameters/<int:pk>/', views.parameter_detail, name='parameter_detail'),
    path('harvests/<int:pk>/', views.harvest_detail, name='harvest_detail'),
    path('daily-records/<int:pk>/edit/', cycle_write_guard(views.edit_daily_record), name='edit_daily_record'),
    path('daily-records/<int:pk>/delete/', cycle_write_guard(views.delete_daily_record), name='delete_daily_record'),
    path('anco/<int:pk>/edit/', cycle_write_guard(views.edit_anco_check), name='edit_anco_check'),
    path('anco/<int:pk>/delete/', cycle_write_guard(views.delete_anco_check), name='delete_anco_check'),
    path('sampling/<int:pk>/edit/', cycle_write_guard(views.edit_sampling_record), name='edit_sampling_record'),
    path('sampling/<int:pk>/delete/', cycle_write_guard(views.delete_sampling_record), name='delete_sampling_record'),
    path('siphon/<int:pk>/edit/', cycle_write_guard(views.edit_siphon_record), name='edit_siphon_record'),
    path('siphon/<int:pk>/delete/', cycle_write_guard(views.delete_siphon_record), name='delete_siphon_record'),
    path('parameters/<int:pk>/edit/', cycle_write_guard(views.edit_parameter), name='edit_parameter'),
    path('parameters/<int:pk>/delete/', cycle_write_guard(views.delete_parameter), name='delete_parameter'),
    path('harvests/<int:pk>/edit/', cycle_write_guard(views.edit_harvest), name='edit_harvest'),
    path('harvests/<int:pk>/delete/', cycle_write_guard(views.delete_harvest), name='delete_harvest'),
]
