# Generated by Django 4.2.30 on 2026-10-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_employee', '0002_aioperationalexpensedocument'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiaction',
            new_name='ai_employee_status_f8ee6c_idx',
            old_name='ai_employee_ai_status_6c1e5a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiaction',
            new_name='ai_employee_action_ff8b0b_idx',
            old_name='ai_employee_ai_action_2e1f9f_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeadvance',
            new_name='ai_employee_employe_d60a88_idx',
            old_name='ai_employee_employe_3b3f5a_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeadvance',
            new_name='ai_employee_advance_3bbe22_idx',
            old_name='ai_employee_advanc_0f2f5c_idx',
        ),
    ]
