# Generated by Django 4.2.30 on 2026-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0003_cycle_production_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationcycle',
            name='target_fcr',
            field=models.DecimalField(decimal_places=2, default=1.2, help_text='Target feed conversion ratio.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='cultivationcycle',
            name='target_population',
            field=models.PositiveBigIntegerField(blank=True, default=0, help_text='Field lama untuk kompatibilitas. Target populasi kini dihitung dari jumlah tebar × target SR.'),
        ),
    ]
