# Generated by Django 4.2.30 on 2026-07-30 13:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrollrecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gaji Pokok'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Upah Harian'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Jumlah Dibayar'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Gaji Pokok/Upah'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='bpjs_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potongan BPJS'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='loan_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potongan Kasbon'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='meal_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Uang Makan'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tunjangan Lain'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potongan Lain'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Lembur'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Potongan Pajak'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Transportasi'),
        ),
        migrations.AlterField(
            model_name='payrollrecord',
            name='work_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hari Kerja'),
        ),
    ]
