from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('ponds','0001_initial'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Stocking', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('seed_count', models.IntegerField()),('hatchery', models.CharField(blank=True, max_length=100)),('notes', models.TextField(blank=True)),('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'))]),
        migrations.CreateModel(name='DailyParameter', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('doc', models.IntegerField(default=0)),('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),('ph_morning', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),('ph_evening', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),('do_morning', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),('do_night', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),('salinity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),('alkalinity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),('transparency', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),('feed_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8)),('mortality', models.IntegerField(default=0)),('water_color', models.CharField(blank=True, max_length=80)),('notes', models.TextField(blank=True)),('ai_recommendation', models.TextField(blank=True)),('created_at', models.DateTimeField(auto_now_add=True)),('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond')),('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='Treatment', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('name', models.CharField(max_length=120)),('dose', models.CharField(blank=True, max_length=80)),('notes', models.TextField(blank=True)),('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'))]),
        migrations.CreateModel(name='FeedLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('feed_name', models.CharField(max_length=100)),('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'))]),
        migrations.CreateModel(name='Harvest', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('date', models.DateField()),('harvest_type', models.CharField(default='Parsial', max_length=30)),('size_text', models.CharField(max_length=50)),('total_kg', models.DecimalField(decimal_places=2, max_digits=10)),('notes', models.TextField(blank=True)),('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponds.pond'))]),
    ]
