# Generated by ChatGPT for Excel-aligned sampling form.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operational_core_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingrecord',
            name='estimated_sr',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimasi SR% FR = Populasi FR / Tebar x 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='index_score',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Index', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='abw_last_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ABW Last, otomatis dari sampling sebelumnya', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='abw_target_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ABW Target = ABW Last + Target ADG x interval hari', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='target_size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target Size = 1000 / ABW Target', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='adg_weekly_target',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ADG Weekly Target', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='sampling_interval_days',
            field=models.PositiveIntegerField(default=0, help_text='Interval hari dari sampling sebelumnya'),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='sr_index_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimasi SR% Index = Populasi Index / Tebar x 100', max_digits=8),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='biomass_index_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biomassa Index = Populasi Index / Size', max_digits=12),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='population_index',
            field=models.PositiveIntegerField(default=0, help_text='Populasi Index'),
        ),
        migrations.AddField(
            model_name='samplingrecord',
            name='daily_feed_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='F/D - Pakan harian', max_digits=10),
        ),
    ]
