# Generated by Django 4.2.30 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_dailyparameter_water_level_cm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocking',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='dailyparameter',
            name='water_level_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='abw_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='ABW Today = Berat / Jumlah', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='adg_cumulative',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ADG Accum = ABW Today / DOC', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='adg_weekly',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ADG Weekly Actual = (ABW Today - ABW Last) / interval hari', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='biomass_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Biomassa FR = F/D / FR x 100', max_digits=12),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='cumulative_feed_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pakan Kumulatif KG', max_digits=12),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='fcr',
            field=models.DecimalField(decimal_places=3, default=0, help_text='FCR = Pakan Kumulatif / Biomassa FR', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='fr_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='FR%', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='population',
            field=models.PositiveIntegerField(default=0, help_text='Populasi FR = Biomassa FR x Size'),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='sample_count',
            field=models.PositiveIntegerField(default=0, help_text='SHRIMP - Jumlah sampel dalam ekor'),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='sample_weight_g',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SHRIMP - Berat sampel total dalam gram', max_digits=10),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Size = 1000 / ABW Today', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='stocking_count',
            field=models.PositiveIntegerField(default=0, help_text='Tebar'),
        ),
    ]
