# Generated by ChatGPT for Smart Shrimp Farm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_dailyparameter_feed_weather_waterin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ancocheck',
            name='feed_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='ancocheck',
            name='daily_feed_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ancocheck',
            name='water_in_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ancocheck',
            name='weather',
            field=models.CharField(blank=True, choices=[('Cerah', 'Cerah'), ('Berawan', 'Berawan'), ('Hujan', 'Hujan'), ('Panas', 'Panas'), ('Angin Kencang', 'Angin Kencang')], max_length=30),
        ),
        migrations.AddField(
            model_name='ancocheck',
            name='treatment',
            field=models.TextField(blank=True),
        ),
    ]
