# Generated by Django 4.2.30 on 2026-07-12 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivation', '0001_initial'),
        ('operations', '0011_backfill_legacy_cycle_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancocheck',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='dailyparameter',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='dailypondrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='feedlog',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='siphonrecord',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_records', to='cultivation.cultivationcycle'),
        ),
    ]
