# Generated by Django 4.2.30 on 2026-07-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0012_alter_ancocheck_cycle_alter_dailyparameter_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingrecord',
            name='adg_weekly',
            field=models.DecimalField(decimal_places=3, default=0, help_text='ADG Weekly Actual = (ABW Today - ABW Last) / 7', max_digits=8),
        ),
        migrations.AlterField(
            model_name='samplingrecord',
            name='fcr',
            field=models.DecimalField(decimal_places=3, default=0, help_text='FCR = Pakan Kumulatif / Biomassa Index', max_digits=8),
        ),
    ]
