# Generated by Django 4.2.30 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_midtrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Transfer', 'Transfer'), ('Tempo', 'Tempo'), ('QRIS', 'QRIS'), ('Midtrans', 'Midtrans')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('Lunas', 'Lunas'), ('Belum Lunas', 'Belum Lunas'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Gagal', 'Gagal'), ('Expired', 'Expired'), ('Dibatalkan', 'Dibatalkan'), ('Refund', 'Refund')], default='Lunas', max_length=20),
        ),
    ]
